drop table CONTACT;
drop table ADDRESS;

create table ADDRESS (
   ADDRESSID INT NOT NULL auto_increment,
   STREET VARCHAR(32),
   CITY VARCHAR(16),
   STATE VARCHAR(16),
   ZIPCODE VARCHAR(16),
   LAST_UPDATED DATE,
   PRIMARY KEY (ADDRESSID)
);

create table CONTACT (
   CONTACTID INT NOT NULL auto_increment,
   FIRSTNAME VARCHAR(32) NOT NULL,
   LASTNAME  VARCHAR(32) NOT NULL,
   EMAIL VARCHAR(32) NOT NULL,
   PHONE BIGINT NOT NULL,
   ADDRESSID INT,
   STATUS INT,
   LAST_UPDATED DATE,
   PRIMARY KEY (CONTACTID),
   FOREIGN KEY CONTADDRID (ADDRESSID)
        REFERENCES ADDRESS (ADDRESSID)
);

